modules:
- name: convert_markdown_folder_to_speech
  enabled: true
  params:
    input_path: "./data/results/doi-song"
    output_path: "./data/results/doi-song-speech"
    language: "vi"
    overwrite: true